baseurl = "https://www.bmpi.dev"
title = "Build My Passive Income"
theme = "hugo-coder"
languagecode = "zh-cn"
defaultcontentlanguage = "zh-cn"

enableRobotsTXT = true
canonifyURLs = true

paginate = 9999
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pluralizelisttitles = false

FootnoteReturnLinkContents = "â†‘"

[markup.goldmark.renderer]
    unsafe= true

[outputs]
  page     = ["HTML", "AMP"]
  home     = ["HTML", "RSS"]
  section  = ["HTML"]
  taxonomyTerm = ["HTML"]
  taxonomy = ["HTML"]

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[params]
    author = "Dawei Ma"
    info1 = "ğŸ“š Lifelong Learner"
    info2 = "ğŸ‘¨â€ğŸ’» Full-Stack Developer"
    info3 = "ğŸ’´ ETF Trader"
    description = "Study + Craft + Invest = BMPI.dev"
    keywords = "life,dev,trade,passive income,money,developer,Self-management,IT technology,investment transactions"
    avatarurl = "images/mdw.png"
    logoImg = "images/bmpi_logo.jpg"
    header = "BMPI.dev"

    twitter = "madawei2699"
    github = "bmpi-dev"
    telegram = "bmpi365"
    zhihu = "improve365"

    favicon_32 = "images/f/favicon-32x32.png"
    favicon_16 = "images/f/favicon-16x16.png"

    # footercontent = "self/dev/money"

    hidecredits = true
    hidecopyright = false

    series = true

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Series see also post count
    maxSeeAlsoItems = 5

    math = true
    custom_css = ["/css/main.css"]
    custom_js = ["/js/lazysizes.min.js", "/js/flying-pages.min.js", "/js/custom.js"]

    dateFormat = "2006-01-02"

    # AMP
    amp = true
    ampElements = ["amp-ad","amp-analytics"]
    themeColor = "#000000"
    adsensePublisher = "ca-pub-1886683614725279"
    googleAnalytics = "UA-154678195-1"

    # OG
    og_image = "images/mdw.png"

# Comments on github issue
[params.utteranc]
    repo = "bmpi-dev/bmpi.dev"
    issue-term = "pathname"
    theme = "github-light"

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/bmpi-dev"
[[params.social]]
    name = "YouTube"
    icon = "fab fa-youtube"
    weight = 2
    url = "https://www.youtube.com/channel/UCbg-Y24Z1H0nONW-bxgzv6w"    
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/madawei2699"
[[params.social]]
    name = "Telegram"
    icon = "fab fa-telegram"
    weight = 4
    url = "https://t.me/s/bmpi365"
[[params.social]]
    name = "WeChat"
    icon = "fab fa-weixin"
    weight = 5
    url = "https://img.bmpi.dev/755b406f-43ae-e382-e13c-547116d3e7d5.png"
[[params.social]]
    name = "ZhiHu"
    icon = "fab fa-zhihu"
    weight = 6
    url = "https://zhuanlan.zhihu.com/improve365"
[[params.social]]
    name = "Newsletter"
    icon = "fas fa-envelope"
    weight = 7
    url = "https://tinyletter.com/i365"
[[params.social]]
    name = "RSS"
    icon = "fas fa-rss"
    weight = 8
    url = "index.xml"
[[params.social]]
    name = "Dev.to"
    icon = "fas fa-dev-to"
    weight = 9
    url = "https://dev.to/madawei2699"

[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
                name = "About"
                weight = 1
                url = "/about/"
            [[languages.en.menu.main]]
                name = "Self"
                weight = 2
                url  = "/self/"
            [[languages.en.menu.main]]
                name = "Dev"
                weight = 3
                url  = "/dev/"
            [[languages.en.menu.main]]
                name = "Money"
                weight = 4
                url  = "/money/"
            [[languages.en.menu.main]]
                name = "Project"
                weight = 5
                url  = "/project/"
            [[languages.en.menu.main]]
                name = "Goal"
                weight = 6
                url  = "/goal/"

    [languages.zh-cn]
        languagename = "Chinese"
        title = "æ„å»ºæˆ‘çš„è¢«åŠ¨æ”¶å…¥"

        [languages.zh-cn.params]
            author = "é©¬å¤§ä¼Ÿ"
            info1 = "ğŸ“š Lifelong Learner"
            info2 = "ğŸ‘¨â€ğŸ’» Full-Stack Developer"
            info3 = "ğŸ’´ ETF Trader"
            description = "é€šè¿‡å­¦ä¹ ï¼ˆGTDã€æ—¶é—´ç®¡ç†ã€çŸ¥è¯†ç®¡ç†ã€å†™ä½œã€è´¢åŠ¡ç®¡ç†ï¼‰ã€æŠ€æœ¯åˆ›é€ ï¼ˆå‰ç«¯ã€åç«¯ã€ç§»åŠ¨ç«¯ã€DevOpsï¼‰ã€æŠ•èµ„ï¼ˆæŒ‡æ•°æŠ•èµ„ã€åŸºé‡‘ã€è‚¡ç¥¨ã€å€ºåˆ¸ï¼‰ã€ç½‘èµšé¡¹ç›®ï¼ˆSEOã€Affiliateã€Media Buyã€Nicheã€ç¤¾äº¤åª’ä½“ï¼‰æ¥å»ºç«‹è¢«åŠ¨æ”¶å…¥"
            keywords = "è‡ªæˆ‘æå‡ã€æ—¶é—´ç®¡ç†ã€GTDã€å†™ä½œã€æ‘„å½±ã€ç¬”è®°ç®¡ç†ã€çŸ¥è¯†ç®¡ç†ã€è´¢åŠ¡ç®¡ç†ã€å…¨æ ˆå¼€å‘ã€æŒ‡æ•°æŠ•èµ„ã€åŸºé‡‘ã€è‚¡ç¥¨ã€å€ºåˆ¸ã€SEOã€Affiliateã€Media Buyã€Nicheã€ç¤¾äº¤åª’ä½“ã€è¢«åŠ¨æ”¶å…¥ã€ç½‘èµš"
            # footercontent = "self/dev/money"

        [languages.zh-cn.menu]
            [[languages.zh-cn.menu.main]]
                name = "Dashboard"
                weight = 1
                url  = "https://datastudio.google.com/reporting/6c3c6d3d-cd2f-4f8c-85e6-c06d672c445b"
            [[languages.zh-cn.menu.main]]
                name = "å…³äº"
                weight = 2
                url = "/about/"
            [[languages.zh-cn.menu.main]]
                name = "å­¦ä¹ "
                weight = 3
                url  = "/self/"
            [[languages.zh-cn.menu.main]]
                name = "æŠ€æœ¯"
                weight = 4
                url  = "/dev/"
            [[languages.zh-cn.menu.main]]
                name = "æŠ•èµ„"
                weight = 5
                url  = "/money/"
            [[languages.zh-cn.menu.main]]
                name = "ä¸ªäººé¡¹ç›®"
                weight = 6
                url  = "/project/"
            [[languages.zh-cn.menu.main]]
                name = "é•¿æœŸç›®æ ‡"
                weight = 7
                url  = "/goal/"
            [[languages.zh-cn.menu.main]]
                name = "æ€è€ƒ"
                weight = 8
                url  = "https://tg.bmpi.dev"
